In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(6, name="input1")
b = tf.constant(4, name="input2")
c = tf.add(a,b, name="add_c")
d = tf.multiply(a,b,name="multiply_d")
e = tf.add(c,d, name="add_e")

In [3]:
e

<tf.Tensor: shape=(), dtype=int32, numpy=34>

In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 [==============================] - 4s 0us/step


In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.08548887,  0.21538399,  0.05716201, -0.35738263,  0.6405635 ,
        -0.00708871,  0.00089833,  0.18804601, -0.3243052 ,  0.00963882]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()


array([[0.08541935, 0.11540474, 0.09851644, 0.065084  , 0.17655368,
        0.09238574, 0.09312659, 0.11229255, 0.06727282, 0.09394413]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [10]:
loss_fn(y_train[:1], predictions).numpy()



2.3817825

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [12]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2924 - accuracy: 0.9157
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1393 - accuracy: 0.9583
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1046 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0853 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0729 - accuracy: 0.9771


In [13]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 1s - loss: 0.0698 - accuracy: 0.9781 - 590ms/epoch - 2ms/step


[0.06980490684509277, 0.9781000018119812]